### ISSUE TITLE
AttributeError on pipeline components?

### ISSUE THREAD

**Issue by bdewilde** [explosion/spaCy#1695]
I'm getting a strange error on v2.0.4 that I did not get on v2.0.3, but haven't yet been able to diagnose. Am also having a hard time reproducing it in a simple, isolated way, so apologies for the vague submission.

One error happens when I try to deepcopy a `Doc`, and a similar one happens when I try to add pipes to a spacy `Language`. Here's a traceback:

```
  File "/home/travis/build/chartbeat-labs/textacy/textacy/corpus.py", line 237, in load
    spacy_lang.add_pipe(spacy_lang.create_pipe(name))
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/spacy/language.py", line 217, in create_pipe
    return factory(self, **config)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/spacy/language.py", line 102, in <lambda>
    'tagger': lambda nlp, **cfg: Tagger(nlp.vocab, **cfg),
  File "pipeline.pyx", line 376, in spacy.pipeline.Tagger.__init__
AttributeError: 'NoneType' object has no attribute 'data'
```

Similarly, here's the tail end of the deepcopy traceback:

```
  File "nn_parser.pyx", line 315, in spacy.syntax.nn_parser.Parser.__init__
AttributeError: 'NoneType' object has no attribute 'data'
```

The most puzzling aspect is that I can run the same code successfully in v2.0.3, so either something changed on your side, or I'm doing something very dumb. Thanks in advance for helping me figure out which. :)

## Your Environment

* **spaCy version:** 2.0.4
* **Platform:** Darwin-16.7.0-x86_64-i386-64bit
* **Python version:** 3.6.0
* **Models:** de, de_core_news_sm, en, en_core_web_sm, es, es_core_news_sm

**Comment by ines** [comment]
Ah, so sorry about this – this seems to be related to a bug we intended to fix in v2.0.4 (but didn't – instead, it ended up still broken, but different). So we pushed another fix earlier. Can you try again with v2.0.5?

Problem in a nutshell: The vectors didn't pickle correctly and ended up being deserialized as zeros. Unfortunately, the fix contained a bug, so the vectors then became `None`, which causes errors like the one above when trying to access `vocab.vectors.data`.

**Comment by bdewilde** [comment]
Aha! That explains why this started working 10 minutes ago, when I updated to v2.0.5. 😁 

Thanks, Ines!
