### PR TITLE
Entity ruler remove pattern

### PR DESCRIPTION
**Pull request by DuyguA**
## Description

Allow removing patterns by their `id` , introduces a new method `remove` to EntityRuler. Fixes #8228

### Types of change

A minor enhancement, also minor addition to docs about the new method.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

File: website/docs/api/entityruler.md [hunk 1]
```diff
@@ -210,6 +210,24 @@ of dicts) or a phrase pattern (string). For more details, see the usage guide on
 | ---------- | ---------------------------------------------------------------- |
 | `patterns` | The patterns to add. ~~List[Dict[str, Union[str, List[dict]]]]~~ |
 
+
+## EntityRuler.remove {#remove tag="method"}
+
+Remove a pattern by its ID from the entity ruler. An `Error` is raised if ID does not exist.
```
Comment (polm) [inline website/docs/api/entityruler.md:216]: This should be `ValueError`, right?

File: spacy/pipeline/entityruler.py [hunk 2]
```diff
@@ -348,6 +348,45 @@ def clear(self) -> None:
...
+            self._create_label(label, eid) for (label, eid) in label_id_pairs
+        ]
+        self.phrase_patterns = defaultdict(
+            list,
+            {
+                label: val
+                for (label, val) in self.phrase_patterns.items()
+                if label not in created_labels
+            },
+        )  # remove the patterns from self.phrase_patterns
```
Comment (polm) [inline spacy/pipeline/entityruler.py:373]: Maybe this is a Black formatting thing, but wouldn't this be easier to read if these comments were above the start of the expression rather than the end?

File: spacy/errors.py [hunk 3]
```diff
@@ -887,6 +887,7 @@ class Errors(metaclass=ErrorsWithCodes):
     E1021 = ("`pos` value \"{pp}\" is not a valid Universal Dependencies tag. "
              "Non-UD tags should use the `tag` property.")
     E1022 = ("Words must be of type str or int, but input is of type '{wtype}'")
+    E1023 = ("A pattern with {ent_id} id is not present in EntityRuler patterns.")
```
Comment (polm) [inline spacy/errors.py:890]: I would use the format `ID \"{ent_id}\"` instead, in case IDs have spaces or something.

**Review by polm — APPROVED** [review]
Tests look good! This will be a nice feature to have.

There are a few small things with comments / text I think could be adjusted but overall this is good.

File: website/docs/api/entityruler.md (hunk 1 above)
Comment (DuyguA) [reply website/docs/api/entityruler.md:216]: Yes, I think I made a tini-mini typo, thanks for pointing out!

File: spacy/errors.py (hunk 3 above)
Comment (DuyguA) [reply spacy/errors.py:890]: Ah, OK!

**Comment by svlandeg** [comment]
@DuyguA : can you look into the failing tests? It might be that you just need some `# type: ignore` statements to make `mypy` happy.

**Comment by DuyguA** [comment]
> @DuyguA : can you look into the failing tests? It might be that you just need some `# type: ignore` statements to make `mypy` happy.

Erghh, no. This is the error message:

```
spacy/pipeline/entityruler.py:385: error: Unsupported right operand type for in ("PhraseMatcher")
spacy/pipeline/entityruler.py:386: error: "PhraseMatcher" has no attribute "remove"
```

This is the failure line:  https://github.com/explosion/spaCy/blob/6d9370baf0dbc2616756c41ec12b800430b97284/spacy/pipeline/entityruler.py#L386
PhraseMatcher and Matcher both have a remove method, I don't know why it fails. It compiles and works on my local machine, Python 3.8. It also passes the Python 3.10 pipeline.




It's totally fine and works on Python 3.10.

**Comment by adrianeboyd** [comment]
To clarify about the python 3.10 and CI: we're skipping the mypy tests for python 3.10 right now because it is too slow without binary wheels. If you ran it locally with 3.10 you should see the same errors as for the other versions of python.

You probably need to look at the `.pyi` files.

**Comment by svlandeg** [comment]
> You probably need to look at the `.pyi` files.

Yes exactly. @DuyguA : I just checked, and the `remove` method is missing from `phrasematcher.pyi`. You can probably fix this by simply copying the definition from `matcher.pyi`, as the types should be the same:
```
def remove(self, key: str) -> None: ...
```

Locally, you can run `mypy` on just one file or module, to quickly check whether that resolves the error.

File: spacy/pipeline/entityruler.py (hunk 2 above)
Comment (DuyguA) [reply spacy/pipeline/entityruler.py:373]: Ah yes, I originally put the comments to the same line then Black moved them to next line. I'll carry them above expressions.

File: website/docs/api/entityruler.md [hunk 4]
```diff
@@ -210,6 +210,24 @@ of dicts) or a phrase pattern (string). For more details, see the usage guide on
 | ---------- | ---------------------------------------------------------------- |
 | `patterns` | The patterns to add. ~~List[Dict[str, Union[str, List[dict]]]]~~ |
 
+
+## EntityRuler.remove {#remove tag="method"}
```
Comment (svlandeg) [inline website/docs/api/entityruler.md:214]:
```suggestion
## EntityRuler.remove {#remove tag="method" new="3.2.1"}
```

File: website/docs/api/entityruler.md [hunk 5]
```diff
@@ -210,6 +210,24 @@ of dicts) or a phrase pattern (string). For more details, see the usage guide on
...
+
+Remove a pattern by its ID from the entity ruler. A `ValueError` is raised if ID does not exist.
```
Comment (svlandeg) [inline website/docs/api/entityruler.md:216]:
```suggestion
Remove a pattern by its ID from the entity ruler. A `ValueError` is raised if the ID does not exist.
```
