### ISSUE TITLE
Usage of "drop" keyword arg in train_new_entity_type example

### ISSUE THREAD

**Issue by MatthieuBizien** [explosion/spaCy#1156]
I can't run train_new_entity_type.py with my mac :

````
± python train_new_entity_type.py en
Loading initial model en
Traceback (most recent call last):
  File "train_new_entity_type.py", line 131, in <module>
    plac.call(main)
  File "/Users/matthieu/env/test_spacy/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/matthieu/env/test_spacy/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_new_entity_type.py", line 113, in main
    train_ner(nlp, train_data, output_directory)
  File "train_new_entity_type.py", line 71, in train_ner
    loss += nlp.entity.update(doc, gold, drop=0.9)
  File "spacy/syntax/parser.pyx", line 306, in spacy.syntax.parser.Parser.update (spacy/syntax/parser.cpp:9619)
TypeError: update() got an unexpected keyword argument 'drop'
````

The en model is installed. It does work on Ubuntu 16.04.

## Your Environment
* **spaCy version:** 1.8.2
* **Platform:** Darwin-16.4.0-x86_64-i386-64bit
* **Python version:** 3.6.1
* **Installed models:** en

**Comment by honnibal** [comment]
The `drop` argument is only on the master branch --- it hasn't made it into a pip release yet, because we focussed on getting the spaCy 2 alpha out.

You might want to try working with the v2 alpha, which can be installed with `pip install spacy-nightly`
