### ISSUE TITLE
Post-training fails in Spacy 2.0 nightly

### ISSUE THREAD

**Issue by adam-ra** [explosion/spaCy#1483]
I'm trying to post-train the main tagger associated with a loaded model. This approach has been working under spacy 1.8.2 and I'm wondering whether this is a bug or a shift in philosophy. Either way, I'd appreciate help on making post-training work again.

spacy-nightly==2.0.0a17
python3

``
import spacy
nlp = spacy.load('en_core_web_sm')

training_data = [
    ('Chest pain', 'NN NN'),
    ('chest pain', 'NN NN'),
    ('Head injury', 'NN NN'),
    ('head injury', 'NN NN'),
]

def update_tagger(tagger, example):
    orth_text, label_text = example
    doc = nlp.tokenizer(orth_text)
    tags = label_text.split()
    assert len(doc) == len(tags), 'Tokenisation does not match tags for {}'.format(orth_text)
    gold = spacy.gold.GoldParse(doc, tags=tags)
    tagger.update(doc, gold)

def train_tagger(tagger, examples, reps):
    for rep in range(reps):
        for example in examples:
            update_tagger(tagger, example)
    tagger.model.end_training()

train_tagger(nlp.tagger, training_data, 100)
``

What happens:
``
  File "x-posttrain.py", line 17, in update_tagger
    tagger.update(doc, gold)
  File "pipeline.pyx", line 383, in spacy.pipeline.NeuralTagger.update
  File "/home/aradziszewski/venvs/nlp-nightly/lib/python3.5/site-packages/thinc/api.py", line 61, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/home/aradziszewski/venvs/nlp-nightly/lib/python3.5/site-packages/thinc/api.py", line 337, in feature_extracter_fwd
    features = [ops.asarray(get_feats(doc), dtype='uint64') for doc in docs]
  File "/home/aradziszewski/venvs/nlp-nightly/lib/python3.5/site-packages/thinc/api.py", line 337, in <listcomp>
    features = [ops.asarray(get_feats(doc), dtype='uint64') for doc in docs]
  File "/home/aradziszewski/venvs/nlp-nightly/lib/python3.5/site-packages/thinc/api.py", line 336, in get_feats
    return doc.doc.to_array(attrs)[doc.start:doc.end]
AttributeError: 'spacy.tokens.token.Token' object has no attribute 'start'
``

**Comment by ines** [comment]
Yes, the approach should still work – you mostly need to adjust a few small things to make it work with the new training API in v2.0.

* Instead of `end_training()` to tell spaCy when to *stop*, you now call `begin_training()`, which returns an optimizer you can pass into `update`.
* All individual pipeline components have an `update` method, which takes a sequence of `docs`, a sequence of `golds`, an optimizer, an optional dropout rate and an optional dictionary to collect the losses.
* You can still get the tagger as `nlp.tagger`, but it's recommended to use `nlp.get_pipe('tagger')` instead and access pipeline components via their string ID. You can now easily add your own pipeline components and rearrange and rename the built-in components ([more details here](https://alpha.spacy.io/usage/processing-pipelines#custom-components)). So for example, if you add your own tagger and rename the built-in to `'spacy_tagger'`, `nlp.tagger` can lead to unexpected results.

Here's a simple dummy training loop in v2.0:

```python
tagger = nlp.get_pipe('tagger')
optimizer = tagger.begin_training()
for i in range(100):
    for doc, gold in examples:
        tagger.update([doc], [gold], sgd=optimizer)
```

You can find a full and updated example of training the tagger in [`examples/training/train_tagger.py`](https://github.com/explosion/spaCy/blob/develop/examples/training/train_tagger.py). Note that this exact example only works with the version currently on `develop`, which will be out as `v2.0.0a18` today (as soon as Travis goes green). This version will also implement an `add_label()` method on the pipeline components that lets you add your own labels and optional values (e.g. for the tag map). So you can do things like: `tagger.add_label('MY_NOUN', {"pos": "NOUN"})`.

**Comment by adam-ra** [comment]
Thanks, @ines  for explanations and a working example!
This allowed me to get pass the exceptions, but I get the impression that the post-training has no effect on the tagger object that is used internally in the `nlp` object.
Unfortunately the new Spacy model is too good :D so none of the items on my known-mistaggings list is any longer valid, I just can't find any issues to correct. So instead I was trying to train it to mislabel things (for the sake of testing) and even 1000 repetitions seems not enough to change the observed behaviour. I'm wondering if there is some issue with object copies / training other instance than using later…

Here is the script I used — and the phrase is still tagged correctly as JJ NN in spite of the (mis-)training effort.

```
#!/usr/bin/env python
import spacy
nlp = spacy.load('en_core_web_sm')

training_data = [
    ('Chest pain', 'NN NN'),
    ('chest pain', 'NN NN'),
    ('Head injury', 'NN NN'),
    ('head injury', 'NN NN'),
    ('swollen finger', 'NN NN'),
]

def update_tagger(tagger, optimizer, example):
    orth_text, label_text = example
    doc = nlp.tokenizer(orth_text)
    tags = label_text.split()
    assert len(doc) == len(tags), 'Tokenisation does not match tags for {}'.format(orth_text)
    gold = spacy.gold.GoldParse(doc, tags=tags)
    tagger.update([doc], [gold], sgd=optimizer)

def train_tagger(tagger, examples, reps):
    optimizer = tagger.begin_training()
    for rep in range(reps):
        for example in examples:
            update_tagger(tagger, optimizer, example)

def _dump(node, lvl=0):
    left_side = '{:2}) {:6} {} {}'.format(
        node.i, node.dep_, '----' * lvl, node.lemma_)
    print('{:36}{:6}{:6}{}'.format(left_side, node.pos_, node.tag_, node.dep_))
    for l_node in node.lefts:
        _dump(l_node, lvl + 1)
    for r_node in node.rights:
        _dump(r_node, lvl + 1)
def dump(par):
    for sent in par.sents:
        _dump(sent.root)


tagger = nlp.get_pipe('tagger')
train_tagger(tagger, training_data, 1000)

dump(nlp('swollen finger'))
```

**Comment by honnibal** [comment]
@adam-ra Aaah, this was quite subtle --- it fooled me too. I've just pushed a fix that makes this much more useable.

The problem was that `Language.begin_training()` returned an optimizer, but the pipeline components didn't --- they returned `None`. Then if you pass `sgd=None` to the pipeline `update()` methods, it doesn't update --- so, nothing was happening.

To fix this, I've made the `begin_training()` methods of the pipeline components return an optimizer. There's also a `create_optimizer()` method you can call to simply, create an optimizer, if you know that's exactly what you want to do.

**Comment by adam-ra** [comment]
@honnibal It seems that more things have changed since last nightly build. I've pulled fresh snapshot off master and now 1) `English` object has no attribute `get_pipe`, 2) nlp.tagger (English object.tagger) has no `begin_training` attribute. Sorry for dwelling on this, but can't really guess how to work this around

**Comment by ines** [comment]
@adam-ra The current alpha version isn't on master yet, so you'll have to pull from `develop`. We're also just preparing the `v2.0.0a19` build, which will include the fix mentioned above.

**Comment by adam-ra** [comment]
@ines Thanks a lot, it works like a charm when pulled from `develop`! Which also means I'm almost there with experimental port of my project to Spacy 2.0 alpha :smiley_cat:

**Comment by adam-ra** [comment]
This sounds great! If I come across some useful feedback from early adoption, I'll share it happily. So far I it seems that the new version works slower than 1.8 in spite of smaller model used (en_core_web_sm v. en_depent_web_md) but it might be some issue with my code, so I need to investigate deeper.
