### ISSUE TITLE
'spacy.tokens.span.Span' object has no attribute 'set_flag'

### ISSUE THREAD

**Issue by easimadi** [explosion/spaCy#2239]
The example below on spacy website doesn't seem to work in spacy v2.0.
I get the error
``` 'spacy.tokens.span.Span' object has no attribute 'set_flag' ```

Code
```python
BAD_HTML_FLAG = nlp.vocab.add_flag(lambda text: False)

matcher = Matcher(nlp.vocab)

def merge_and_flag(matcher, doc, i, matches):
    match_id, start, end = matches[i]
    span = doc[start : end]
    span.merge(is_stop=True) # merge (and mark it as a stop word, just in case)
    span.set_flag(BAD_HTML_FLAG, True) # set BAD_HTML_FLAG

matcher.add('BAD_HTML', merge_and_flag,
            [{'ORTH': '<'}, {'LOWER': 'br'}, {'ORTH': '>'}],
            [{'ORTH': '<'}, {'LOWER': 'br/'}, {'ORTH': '>'}])

doc = nlp('<br> is bad in text')
```

## Your Environment

* Operating System: 
linux
* Python Version Used: 
python 3
* spaCy Version Used:
v2.0 
* Environment Information:

**Comment by ines** [comment]
Thanks for the report! No idea how this happened. Instead of using the span, we should probably loop over the tokens and set the flag on each of them. Since the `span` is merged, it will only contain one token – but I think looping over the tokens might still be cleaner, since it means the example will also work if you choose *not* to merge the span. 

```python
for token in span:
    token.set_flag(BAD_HTML_FLAG, True) # set BAD_HTML_FLAG
```

**Comment by ines** [comment]
Fixed in #2274!
