### ISSUE TITLE
Issues upgrading from v1.9 to v2

### ISSUE THREAD

**Issue by lioryaffe** [explosion/spaCy#1584]
Hi,
so after yesterday's issues: https://github.com/explosion/spaCy/issues/1575
i thought I'm on the right path, but i'm still facing some annoying issues with the code which worked on 1.9

the most annoying thing, is that while looping on the train files,
sometimes after 
`nlp.entity.update([doc],[gold])`
the pycharm process is existing and i'm getting

> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

each time is after a different file

even when i succeeded to finish the training, when trying to save the model to the disk with
`nlp.to_disk(output_dir)`
i'm getting

> 'WhitespaceTokenizer' object has no attribute 'to_disk'

* Python Version Used: 3.6
* spaCy Version Used: 2.0

**Comment by ines** [comment]
> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

Sorry about this – this is a C-level error that can be caused by various things, and is hard to debug without more details. 

Do you get the same error if you're training with spaCy's default tokenizer instead of your custom one? This could indicate that the custom tokenizer might be producing invalid tokens, or the length of the `Doc` and `Gold` objects doesn't match up.

We're also about to push an update to spaCy (v2.0.3) which includes some fixes that may have an impact on the issue.

> 'WhitespaceTokenizer' object has no attribute 'to_disk'

This happens because by default, spaCy will serialize all pipeline components, plus the `Vocab` and the `Tokenizer`. This is done by calling the component's `to_disk()` method. You can find an explanation of this in #1557 – it's related to the custom Japanese tokenizer, but the underlying issue is the same.

In your case, you're using a custom tokenizer, `WhitespaceTokenizer`, which doesn't have serialization methods. Here are the two easiest solutions for this:

1. When you save the model to disk, use `nlp.to_disk('/path/to/model', disable=['tokenizer'])`. This will prevent spaCy from trying to serialize data from your custom tokenizer. When you load the model back in, you'll obviously need to add your custom tokenizer back. (If you're looking to generate a model package, you can also ship your tokenizer with the model package – see [this section](https://spacy.io/usage/training#models-custom) in the docs for more info).

2. Implement a dummy serialization method on your `WhitespaceTokenizer` that returns `None` (or, if you do want to serialize data, a bytestring of the data). This is how the custom Japanese tokenizer currently does it (see c9d72de0fb9814e39971ce79d32d62b21c425154):

```python
def to_disk(self, path, **exclude):
    return None
```

**Comment by lioryaffe** [comment]
> Do you get the same error if you're training with spaCy's default tokenizer instead of your custom one? This could indicate that the custom tokenizer might be producing invalid tokens, or the length of the Doc and Gold objects doesn't match up.

The suprising part is that it's not deterministic - the same file could one time pass, and another time to cause this error.
Also, I have to use my own tokenizer, otherwise my training files (which are already tokenized - one word per line with a tag) doesn't match...

**Comment by ines** [comment]
> Also, I have to use my own tokenizer, otherwise my training files (which are already tokenized - one word per line with a tag) doesn't match...

Ah okay – you should be able to circumvent this by adding a `words` keyword argument to the `GoldParse` that specifies the correct, gold-standard tokenization. For example: 

```python
doc = nlp.make_doc("helloworld")
gold = GoldParse(doc, words=["hello", "world"], entities=entities)
nlp.update([doc], [gold])
```

So you might even be able to kill two birds with one stone: you can kick out the custom tokenizer and won't have to worry about the serialization, and if you're lucky, it might even solve the segmentation fault (because a possible theory is that it's caused by an interaction with the custom tokenizer, or an underlying bug that only occurs during training with a specific configuration for tokenization – but as you've seen, those errors are often very tricky to debug, because they're difficult to reproduce and isolate).

**Comment by lioryaffe** [comment]
Even after removing the costume tokenizer, still getting the exit code 139 exception.

Only one time my training has done, but the test was not good, and it found a lot of junk.
I took a look on the vocabulary size of the v1.9 and the v2 and I also see difference there...

**Comment by ines** [comment]
The segmentation fault ("Process finished with exit code 139") was likely related to ad068f51be6a2579c19c35bcd8b5c1767441ffc1, which is now fixed (if not, feel free to reopen).
