### ISSUE TITLE
When available for Python 3.9 

### ISSUE THREAD

**Issue by hadDOTpy** [explosion/spaCy#8087]
I'm Having issues with `AttributeError: module 'time' has no attribute 'clock'`

**Comment by polm** [comment]
spaCy works with Python 3.9. From your description I'm not clear what your problem is.

Since this doesn't sound like a bug I'm moving it to Discussions, click the link to follow up there.
