### ISSUE TITLE
AttributeError: 'Lookups' object has no attribute 'get' -> after upgrade to spacy v2.2.2.

### ISSUE THREAD

**Issue by filipdbrsk** [explosion/spaCy#4574]
After upgrading spacy to v2.2.2 with pip, the Dutch model fails to parse documents. Perhaps this method got lost during the update?
## How to reproduce the behaviour
```
import nl_core_news_sm
spacy_nl = nl_core_news_sm.load()
text='Aucula tusora is een vlinder uit de familie van de uilen (Noctuidae). De wetenschappelijke naam van de soort is voor het eerst geldig gepubliceerd in 1981 door Todd & Poole.'spacy_nl = doc_nl=spacy_nl(text)
```
--------
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fii800/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "pipes.pyx", line 396, in spacy.pipeline.pipes.Tagger.__call__
  File "pipes.pyx", line 441, in spacy.pipeline.pipes.Tagger.set_annotations
  File "morphology.pyx", line 307, in spacy.morphology.Morphology.assign_tag_id
  File "morphology.pyx", line 241, in spacy.morphology.Morphology.lemmatize
  File "/home/fii800/anaconda3/lib/python3.7/site-packages/spacy/lang/nl/lemmatizer/lemmatizer.py", line 47, in __call__
    lemma_index = self.index.get(univ_pos, {})
AttributeError: 'Lookups' object has no attribute 'get'
```

## Your Environment

* Operating System: Ubuntu 18.04
* Python Version Used: 3.7
* spaCy Version Used: 2.2.2
* Environment Information:

**Comment by ines** [comment]
This is strange, I can't reproduce this? 🤔 And I can't find the code it's referring to in the traceback. Is it possible that you somehow ended up with outdated files in your spaCy installation? Which version did you upgrade from?

**Comment by filipdbrsk** [comment]
You are right. My conda environment seems to be messed up. I tried on another server and then it worked. Thanks!
