### ISSUE TITLE
span has no attribute 'ents' v2.0.11 

### ISSUE THREAD

**Issue by wxv** [explosion/spaCy#2986]
#2589 Works in v2.0.12, not v2.0.11. So docs should reflect that this feature was added and the workaround. 

## How to reproduce the behaviour

```
import spacy

nlp = spacy.load('en_core_web_sm')
doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')
span = doc[:3]
print(span.ents) 
# AttributeError: 'spacy.tokens.span.Span' object has no attribute 'ents'
```
Workaround is converting Span back to Doc: `span.as_doc().ents` 

## Your Environment
* **spaCy version:** 2.0.11
* **Platform:** Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
* **Python version:** 3.6.6
* **Models:** xx_ent_wiki_sm, en_core_web_md, en

**Comment by ines** [comment]
Thanks a lot! We normally use tags like "new in spaCy v2.x" in the docs to note when new features were introduced. Looks like we forgot this here: https://spacy.io/api/span#ents

Will fix 👍
