### ISSUE TITLE
Doc.to_disk() exception

### ISSUE THREAD

**Issue by davidgengenbach** [explosion/spaCy#1521]
First of all, thanks for your library!

I have a problem serializing docs. Here is a minimal example of what I want to do:
```python
import spacy
nlp = spacy.load('en')
texts = ['The brown fox jumped over the fence.', 'The fence was not that tall anyways.']
docs = nlp.pipe(texts)
# Here I want to save the docs to the disk
list(docs)[0].to_disk('some_file')
```
but I get the following exception:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-449d2fe86bdf> in <module>()
      4 texts = ['The brown fox jumped over the fence.', 'The fence was not that tall anyways.']
      5 docs = nlp.pipe(texts)
----> 6 list(docs)[0].to_disk('some_file')

doc.pyx in spacy.tokens.doc.Doc.to_disk()

AttributeError: 'str' object has no attribute 'open'
```
What is the correct way to save multiple documents when using `nlp.pipe(texts)`? I also tried doing it like this:
```python
import spacy
import pickle

nlp = spacy.load('en')
texts = ['The brown fox jumped over the fence.', 'The fence was not that tall anyways.']
docs = nlp.pipe(texts)
docs_b = [doc.to_bytes() for doc in docs]
with open('some_file', 'wb') as f:
    pickle.dump(docs_b, f)
```
But this produces quite large files (I assume it also saves the model with it?).

Again, thanks for the library, your work and maybe answering this question! 👍 

## Your Environment
* **spaCy version:** 2.0.2
* **Platform:** Darwin-17.0.0-x86_64-i386-64bit (macOS 10.13)
* **Python version:** 3.6.2
* **Models:** en

**Comment by davidgengenbach** [comment]
Ah, I am sorry. I just saw that just pickling the Docs now works with spaCy 2.0.

I am leaving this issue nevertheless - maybe somebody also runs into this problem when migrating to spaCy 2.0.

```python
import spacy
import pickle

nlp = spacy.load('en')
texts = ['The brown fox jumped over the fence.', 'The fence was not that tall anyways.']
docs = nlp.pipe(texts)
with open('some_file', 'wb') as f:
    pickle.dump(list(docs), f)
```

**Comment by honnibal** [comment]
Thanks! It looks like there's a bug in `doc.to_disk()`: it's expecting a `pathlib.Path()` object, when it should also accept a string. 

In general I think you'll find the `doc.to_bytes()` method to be the best way to serialize `Doc` objects. It lets you do the i/o, and it should be faster and smaller than pickle.

**Comment by davidgengenbach** [comment]
Thanks for answering so quickly and for the quick bug fix!

I still have a little problem with the file size of the serialized docs - here is a graph of what I mean:

![spacy_file_sizes](https://user-images.githubusercontent.com/2621491/32603224-3506c746-c549-11e7-8c77-3567658cabdc.png)

Both the `doc.to_bytes()` and the plain saving with pickle create quite big files! For just 500 documents, the size of the serialized docs is above 400mb! Is there a way to serialize the documents all at once without such big file sizes?

**Comment by zicklag** [comment]
If I use the `doc.to_bytes()` to export the doc, do I still have to export the `Vocab` object separately from the `Doc` or is it included?

**Comment by bdewilde** [comment]
fwiw I'm also running into some of the issues described above. Previously, users could write multiple `Doc`s to a single file with

```
with open(filepath, mode='wb') as f:
    for doc in docs:
        f.write(doc.to_bytes())
```

then read those docs back in via `Doc.read_bytes()`, which took care of segmenting the file's bytes into individual `Doc`s:

```
docs = []
with open(filepath, mode='rb') as f:
    for bytes_string in Doc.read_bytes(f):
        docs.append(Doc(Vocab).from_bytes(bytes_string))
```

But this no longer works in spacy v2, since `Doc.read_bytes()` has been removed, and the individual docs' byte strings contain newlines, so this can't be done easily in the style of JSONL files.

Is there a recommended way to save multiple `Doc`s together in the same file? As far as I can tell, the documentation only covers the single `Doc` case.

**Comment by bdewilde** [comment]
After looking into the `Doc.to_bytes()` and `Doc.from_bytes()` source code, I don't see any decent way to write+read multiple `Doc`s as bytes from the same file. (Full disclosure: I'm not experienced with `msgpack`, and a couple hours with the docs and examples of its usage in the wild didn't prove particularly insightful.)

As I wrote above, it's straightforward to write multiple docs-as-bytes out to the same file, but the old way of reading the data back in no longer works, and the way the methods are written (with corresponding `util.to_bytes()`, `util.from_bytes()` functions) seems to force a one-`Doc`-per-file use case.

For example, this too-easy option doesn't work:

```
docs = []
with io.open(fname, mode='rb') as f:
    for line in f:
        docs.append(Doc(Vocab()).from_bytes(line))
```

Although you can use `msgpack.Unpacker` to iterate over the stored objects one-by-one, these objects are unpacked dicts incompatible with the expected inputs for the existing `Doc` methods:

```
with io.open(fname, mode='rb') as f:
    unpacker = msgpack.Unpacker(f)
    for obj in unpacker:
        print(obj.keys())
        break
```

Here, `obj.keys()` => `dict_keys(['text', 'array_head', 'array_body', 'sentiment', 'tensor'])`. I believe this is equivalent to `msg` in [this line](https://github.com/explosion/spaCy/blob/master/spacy/tokens/doc.pyx#L803) midway through `Doc.from_bytes()`, since the deserializers are all null-op lambdas and the docs don't have any user_data. But to initialize new docs from these dicts, I'd have to effectively duplicate much of the code elsewhere in `Doc.from_bytes()`, which seems like a bad idea.

I looked to `pandas` [for inspiration](https://pandas.pydata.org/pandas-docs/stable/io.html#msgpack), but [the code](https://github.com/pandas-dev/pandas/tree/master/pandas/io/msgpack) was sufficiently complicated that I didn't get very far.

I should note that pickling _does_ work, which is great, but you have to write all the docs out at once as a list (load them all into memory...), and the file size is surprisingly large, as somebody pointed out above.

This issue is my last blocker to making `textacy` compatible with v2, and I haven't found any good options. Maybe (hopefully) I've missed something in the docs, or github, or gitter chat.

@honnibal , do you have any suggestions? 🙏
