### ISSUE TITLE
2.0.13/14 issues with thinc dependecies

### ISSUE THREAD

**Issue by stas00** [explosion/spaCy#2849]
## Your Environment

* Operating System: Linux and Mac
* Python Version Used: 3.6 and 3.7
* spaCy Version Used: 2.0.13/2.0.14

The 2.0.14 release seemed to breaks fastai test suite, it was working fine before this release.

I'm trying to figure out the dependencies pull, I think it may have to do with an incompatible thinc it pulled in. Unfortunately not shell access on CI builds so it's a slow figuring out :( 

Everything works just fine on my personal linux box with identical setup.

You can see the log/env from make test here:
https://dev.azure.com/fastdotai/fastai/_build/results?buildId=204&view=logs
but also for your convenience pasted it below:

The failing test is here: https://github.com/fastai/fastai/blob/master/tests/test_core.py

The log is here:
```
Task         : Command Line
Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
Version      : 2.136.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
Generating script.
Script contents:
py.test tests --cache-clear --junitxml=result.xml
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/47cc088b-e9cb-4f34-8970-0827aa125f96.sh
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.8.2, py-1.7.0, pluggy-0.7.1
rootdir: /home/vsts/work/1/s, inifile: setup.cfg
collected 1 item / 7 errors

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_core.py ______________________
tests/test_core.py:3: in <module>
    from fastai import *
fastai/__init__.py:1: in <module>
    from .basic_train import *
fastai/basic_train.py:2: in <module>
    from .torch_core import *
fastai/torch_core.py:2: in <module>
    from .imports.torch import *
fastai/imports/__init__.py:1: in <module>
    from .core import *
fastai/imports/core.py:6: in <module>
    import html, re, spacy, requests
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/__init__.py:7: in <module>
    from .cli.info import info as cli_info
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/__init__.py:1: in <module>
    from .download import download
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/download.py:11: in <module>
    from .link import link
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/link.py:8: in <module>
    from ..compat import symlink_to, path2str
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/compat.py:9: in <module>
    from thinc.neural.util import copy_array
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/__init__.py:1: in <module>
    from ._classes.model import Model
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/_classes/model.py:12: in <module>
    from ..train import Trainer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/train.py:3: in <module>
    from .optimizers import Adam, SGD, linear_decay
optimizers.pyx:13: in init thinc.neural.optimizers
    ???
cymem.pxd:4: in init thinc.neural.ops
    ???
E   AttributeError: module 'cymem.cymem' has no attribute 'PyMalloc'
____________________ ERROR collecting tests/test_fastai.py _____________________
tests/test_fastai.py:1: in <module>
    import pytest,fastai
fastai/__init__.py:1: in <module>
    from .basic_train import *
fastai/basic_train.py:2: in <module>
    from .torch_core import *
fastai/torch_core.py:2: in <module>
    from .imports.torch import *
fastai/imports/__init__.py:1: in <module>
    from .core import *
fastai/imports/core.py:6: in <module>
    import html, re, spacy, requests
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/__init__.py:7: in <module>
    from .cli.info import info as cli_info
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/__init__.py:1: in <module>
    from .download import download
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/download.py:11: in <module>
    from .link import link
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/link.py:8: in <module>
    from ..compat import symlink_to, path2str
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/compat.py:32: in <module>
    from thinc.neural.optimizers import Optimizer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/__init__.py:1: in <module>
    from ._classes.model import Model
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/_classes/model.py:12: in <module>
    from ..train import Trainer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/train.py:3: in <module>
    from .optimizers import Adam, SGD, linear_decay
optimizers.pyx:13: in init thinc.neural.optimizers
    ???
stringsource:104: in init thinc.neural.ops
    ???
E   AttributeError: type object 'thinc.neural.ops.array' has no attribute '__reduce_cython__'
_____________________ ERROR collecting tests/test_links.py _____________________
tests/test_links.py:2: in <module>
    from fastai.gen_doc import gen_notebooks
fastai/__init__.py:1: in <module>
    from .basic_train import *
fastai/basic_train.py:2: in <module>
    from .torch_core import *
fastai/torch_core.py:2: in <module>
    from .imports.torch import *
fastai/imports/__init__.py:1: in <module>
    from .core import *
fastai/imports/core.py:6: in <module>
    import html, re, spacy, requests
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/__init__.py:7: in <module>
    from .cli.info import info as cli_info
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/__init__.py:1: in <module>
    from .download import download
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/download.py:11: in <module>
    from .link import link
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/link.py:8: in <module>
    from ..compat import symlink_to, path2str
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/compat.py:32: in <module>
    from thinc.neural.optimizers import Optimizer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/__init__.py:1: in <module>
    from ._classes.model import Model
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/_classes/model.py:12: in <module>
    from ..train import Trainer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/train.py:3: in <module>
    from .optimizers import Adam, SGD, linear_decay
optimizers.pyx:13: in init thinc.neural.optimizers
    ???
stringsource:104: in init thinc.neural.ops
    ???
E   AttributeError: type object 'thinc.neural.ops.array' has no attribute '__reduce_cython__'
__________________ ERROR collecting tests/test_torch_core.py ___________________
tests/test_torch_core.py:1: in <module>
    import pytest, torch, fastai
fastai/__init__.py:1: in <module>
    from .basic_train import *
fastai/basic_train.py:2: in <module>
    from .torch_core import *
fastai/torch_core.py:2: in <module>
    from .imports.torch import *
fastai/imports/__init__.py:1: in <module>
    from .core import *
fastai/imports/core.py:6: in <module>
    import html, re, spacy, requests
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/__init__.py:7: in <module>
    from .cli.info import info as cli_info
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/__init__.py:1: in <module>
    from .download import download
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/download.py:11: in <module>
    from .link import link
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/link.py:8: in <module>
    from ..compat import symlink_to, path2str
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/compat.py:32: in <module>
    from thinc.neural.optimizers import Optimizer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/__init__.py:1: in <module>
    from ._classes.model import Model
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/_classes/model.py:12: in <module>
    from ..train import Trainer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/train.py:3: in <module>
    from .optimizers import Adam, SGD, linear_decay
optimizers.pyx:13: in init thinc.neural.optimizers
    ???
stringsource:104: in init thinc.neural.ops
    ???
E   AttributeError: type object 'thinc.neural.ops.array' has no attribute '__reduce_cython__'
_____________________ ERROR collecting tests/test_utils.py _____________________
tests/test_utils.py:1: in <module>
    import pytest, torch, re, fastai
fastai/__init__.py:1: in <module>
    from .basic_train import *
fastai/basic_train.py:2: in <module>
    from .torch_core import *
fastai/torch_core.py:2: in <module>
    from .imports.torch import *
fastai/imports/__init__.py:1: in <module>
    from .core import *
fastai/imports/core.py:6: in <module>
    import html, re, spacy, requests
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/__init__.py:7: in <module>
    from .cli.info import info as cli_info
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/__init__.py:1: in <module>
    from .download import download
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/download.py:11: in <module>
    from .link import link
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/link.py:8: in <module>
    from ..compat import symlink_to, path2str
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/compat.py:32: in <module>
    from thinc.neural.optimizers import Optimizer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/__init__.py:1: in <module>
    from ._classes.model import Model
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/_classes/model.py:12: in <module>
    from ..train import Trainer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/train.py:3: in <module>
    from .optimizers import Adam, SGD, linear_decay
optimizers.pyx:13: in init thinc.neural.optimizers
    ???
stringsource:104: in init thinc.neural.ops
    ???
E   AttributeError: type object 'thinc.neural.ops.array' has no attribute '__reduce_cython__'
____________________ ERROR collecting tests/test_vision.py _____________________
tests/test_vision.py:2: in <module>
    from fastai import *
fastai/__init__.py:1: in <module>
    from .basic_train import *
fastai/basic_train.py:2: in <module>
    from .torch_core import *
fastai/torch_core.py:2: in <module>
    from .imports.torch import *
fastai/imports/__init__.py:1: in <module>
    from .core import *
fastai/imports/core.py:6: in <module>
    import html, re, spacy, requests
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/__init__.py:7: in <module>
    from .cli.info import info as cli_info
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/__init__.py:1: in <module>
    from .download import download
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/download.py:11: in <module>
    from .link import link
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/link.py:8: in <module>
    from ..compat import symlink_to, path2str
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/compat.py:32: in <module>
    from thinc.neural.optimizers import Optimizer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/__init__.py:1: in <module>
    from ._classes.model import Model
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/_classes/model.py:12: in <module>
    from ..train import Trainer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/train.py:3: in <module>
    from .optimizers import Adam, SGD, linear_decay
optimizers.pyx:13: in init thinc.neural.optimizers
    ???
stringsource:104: in init thinc.neural.ops
    ???
E   AttributeError: type object 'thinc.neural.ops.array' has no attribute '__reduce_cython__'
_________________ ERROR collecting tests/test_vision_train.py __________________
tests/test_vision_train.py:2: in <module>
    from fastai import *
fastai/__init__.py:1: in <module>
    from .basic_train import *
fastai/basic_train.py:2: in <module>
    from .torch_core import *
fastai/torch_core.py:2: in <module>
    from .imports.torch import *
fastai/imports/__init__.py:1: in <module>
    from .core import *
fastai/imports/core.py:6: in <module>
    import html, re, spacy, requests
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/__init__.py:7: in <module>
    from .cli.info import info as cli_info
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/__init__.py:1: in <module>
    from .download import download
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/download.py:11: in <module>
    from .link import link
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/cli/link.py:8: in <module>
    from ..compat import symlink_to, path2str
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/spacy/compat.py:32: in <module>
    from thinc.neural.optimizers import Optimizer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/__init__.py:1: in <module>
    from ._classes.model import Model
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/_classes/model.py:12: in <module>
    from ..train import Trainer
/opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/site-packages/thinc/neural/train.py:3: in <module>
    from .optimizers import Adam, SGD, linear_decay
optimizers.pyx:13: in init thinc.neural.optimizers
    ???
stringsource:104: in init thinc.neural.ops
    ???
E   AttributeError: type object 'thinc.neural.ops.array' has no attribute '__reduce_cython__'
```

**Comment by stas00** [comment]
On 2018-10-14 04:34 PM, Matthew Honnibal wrote:
> As part of the wheel update, we had to release a version of our memory
> pool package cymem, which is a C-level dependency of spaCy, thinc and
> our hash table preshed. We made the new version of cymem v2.0, which
> spaCy shouldn't resolve as a dependency. Unfortunately, we only pushed
> the Thinc update as 6.10.6. It seems pip didn't do what we expected
> here: even though spaCy is incompatible with Thinc 6.10.6 because they
> can't agree on a version of cymem.
> 
> In short: The update causes spaCy 2.0.13 to install incorrectly, because
> it now gets confused by the new version of Thinc :(.
> 
> v2.0.14 of spaCy is out now, and shouldn't have these problems. I see
> you're requiring exactly spaCy 2.0.13. Can you require 2.0.14?

Oh, I tried to downgrade to 2.0.13, since I thought 2.0.14 was the
culprit. We don't need to require 2.0.13.

I guess pypi wasn't updating its cache - I saw it doing it before - i.e.
not making the release available right away for updates, but showing it
live on their site.

Yes, I have just traced it to  cymem==2.0.2 on my machine and
cymem-1.31.2 on the build.

I have just tested a CI build with spacy (no pin) and cymem==2.0.2 and
it worked.

but I guess I will change it to spacy>=2.0.14 and no cymem at all.

Thank you for your feedback and suggestions, Matthew!



-- 
________________________________________________
Stas Bekman       <'))))><       <'))))><
https://stasosphere.com  https://chestofbooks.com
https://experientialsexlab.com https://stason.org
https://stasosphere.com/experience-life/my-books

**Comment by honnibal** [comment]
Hm `pip install spacy==2.0.12` is now broken :(. So anyone with a precise pin would wake up to broken builds.

Fixing. We're unpublishing Thinc 6.10.6, republishing as Thinc 6.12.0, and pushing spacy 2.0.15

**Comment by stas00** [comment]
On 2018-10-14 04:42 PM, Stas Bekman wrote:
> On 2018-10-14 04:34 PM, Matthew Honnibal wrote:
>> As part of the wheel update, we had to release a version of our memory
>> pool package cymem, which is a C-level dependency of spaCy, thinc and
>> our hash table preshed. We made the new version of cymem v2.0, which
>> spaCy shouldn't resolve as a dependency. Unfortunately, we only pushed
>> the Thinc update as 6.10.6. It seems pip didn't do what we expected
>> here: even though spaCy is incompatible with Thinc 6.10.6 because they
>> can't agree on a version of cymem.
>>
>> In short: The update causes spaCy 2.0.13 to install incorrectly, because
>> it now gets confused by the new version of Thinc :(.
>>
>> v2.0.14 of spaCy is out now, and shouldn't have these problems. I see
>> you're requiring exactly spaCy 2.0.13. Can you require 2.0.14?
> 
> Oh, I tried to downgrade to 2.0.13, since I thought 2.0.14 was the
> culprit. We don't need to require 2.0.13.
> 
> I guess pypi wasn't updating its cache - I saw it doing it before - i.e.
> not making the release available right away for updates, but showing it
> live on their site.
> 
> Yes, I have just traced it to  cymem==2.0.2 on my machine and
> cymem-1.31.2 on the build.
> 
> I have just tested a CI build with spacy (no pin) and cymem==2.0.2 and
> it worked.

On linux. On Mac it breaks with:
 ImportError: cannot import name 'Optimizer'
 ImportError: cannot import name 'Adam'

logs under make test here:
https://dev.azure.com/fastdotai/fastai/_build/results?buildId=208&view=logs

going to test dependencies: spacy>=2.0.14 and no cymem at all next.

-- 
________________________________________________
Stas Bekman       <'))))><       <'))))><
https://stasosphere.com  https://chestofbooks.com
https://experientialsexlab.com https://stason.org
https://stasosphere.com/experience-life/my-books

**Comment by honnibal** [comment]
Well you can't just not use cymem...It won't even compile. Stand by :). 2.0.15 will be up as soon as the build finishes, maybe 10 minutes.

**Comment by stas00** [comment]
On 2018-10-14 04:45 PM, Matthew Honnibal wrote:
> Well you can't just not use cymem...It won't even compile. Stand by :).
> 2.0.15 will be up as soon as the build finishes, maybe 10 minutes.

Sorry, I wasn't clear in my communication, I meant I removed it from
fastai deps and let spacy handle it. When I was trying to figure out why
it was working on my box but not on CI, I compared the package versions
and cymem was the only one different. Hence I was testing with making an
explicit requirement out of it, whereas it wasn't before. And that
worked on linux, but failed on mac.

Note that building with "pip install spacy==2.0.14" fails too:

No matching distribution found for thinc<6.11.0,>=6.10.6 (from
spacy>=2.0.14->fastai==1.0.6.dev0)

If you want full logs:
https://dev.azure.com/fastdotai/fastai/_build/results?buildId=209&view=logs

So I will try again once 2.0.15 is out.

Thank you for your support, Matt.

-- 
________________________________________________
Stas Bekman       <'))))><       <'))))><
https://stasosphere.com  https://chestofbooks.com
https://experientialsexlab.com https://stason.org
https://stasosphere.com/experience-life/my-books

**Comment by honnibal** [comment]
We've unpublished the problematic version of Thinc, so 2.0.12 and 2.0.13 should work again.

**Comment by stas00** [comment]
On 2018-10-14 04:51 PM, Stas Bekman wrote:

> Note that building with "pip install spacy==2.0.14" fails too:
> 
> No matching distribution found for thinc<6.11.0,>=6.10.6 (from
> spacy>=2.0.14->fastai==1.0.6.dev0)

Heh, and you deleted 2.0.14 from pypi ;)

I will let you work and wait for 2.0.15.

The CI build will pick it automatically once you release it since now
it's set to spacy>=2.0.14 and there is no 2.0.14 anymore.

-- 
________________________________________________
Stas Bekman       <'))))><       <'))))><
https://stasosphere.com  https://chestofbooks.com
https://experientialsexlab.com https://stason.org
https://stasosphere.com/experience-life/my-books

**Comment by honnibal** [comment]
Hm, the wheels are queued for v2.0.15 so now that 2.0.13 is fine I think it's better to do the 2.0.15 release tomorrow. It's 2am Sunday night now, which seems a not-so-fine time to release software :p

**Comment by stas00** [comment]
On 2018-10-14 05:01 PM, Matthew Honnibal wrote:
> Hm, the wheels are queued for v2.0.15 so now that 2.0.13 is fine I think
> it's better to do the 2.0.15 release tomorrow. It's 2am Sunday night
> now, which seems a not-so-fine time to release software :p

Yes, of course!

It's totally fine here now, I have it set to spacy<=2.0.13 and all is
fine. I guess I don't need the pin at all at the moment.

Thank you and Good night, Matt.

-- 
________________________________________________
Stas Bekman       <'))))><       <'))))><
https://stasosphere.com  https://chestofbooks.com
https://experientialsexlab.com https://stason.org
https://stasosphere.com/experience-life/my-books

**Comment by ines** [comment]
Fixed a few more things and published `v2.0.16` with wheels for all our packages 🎉 So this issue should be resolved now.

**Comment by stas00** [comment]
Excellent. It works. Thank you!

**Comment by cegprakash** [comment]
Hi I upgraded to 2.0.16 because of this issue but I get another issue because of this

  File "/home/cegprakash/workspace/python-engine/keyword_strategy.py", line 4, in <module>
    import spacy
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/__init__.py", line 10, in <module>
    from .cli.info import info as cli_info
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/cli/download.py", line 11, in <module>
    from .link import link
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..compat import symlink_to, path2str
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/compat.py", line 32, in <module>
    from thinc.neural.optimizers import Optimizer
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
    from ..train import Trainer
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/train.py", line 3, in <module>
    from .optimizers import Adam, SGD, linear_decay
  File "optimizers.pyx", line 13, in init thinc.neural.optimizers
  File "stringsource", line 104, in init thinc.neural.ops
AttributeError: type object 'thinc.neural.ops.array' has no attribute '__reduce_cython__'

Linking #2439 for reference

**Comment by cegprakash** [comment]
Hi I upgraded to 2.0.16 because of this issue but I get another issue because of this

```
  File "/home/cegprakash/workspace/python-engine/keyword_strategy.py", line 4, in <module>
    import spacy
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/__init__.py", line 10, in <module>
    from .cli.info import info as cli_info
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/cli/download.py", line 11, in <module>
    from .link import link
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/cli/link.py", line 8, in <module>
    from ..compat import symlink_to, path2str
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/spacy/compat.py", line 32, in <module>
    from thinc.neural.optimizers import Optimizer
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
    from ..train import Trainer
  File "/home/cegprakash/.local/share/virtualenvs/python-engine-USisEXbk/lib/python3.5/site-packages/thinc/neural/train.py", line 3, in <module>
    from .optimizers import Adam, SGD, linear_decay
  File "optimizers.pyx", line 13, in init thinc.neural.optimizers
  File "stringsource", line 104, in init thinc.neural.ops
AttributeError: type object 'thinc.neural.ops.array' has no attribute '__reduce_cython__'
```

Linking #2439 for reference. Can we reopen this?
