### ISSUE TITLE
spacy gives Segmentation fault (core dumped) when trying to use gpu

### ISSUE THREAD

**Issue by jlealtru** [explosion/spaCy#4821]
## Spacy 2.2.3 with GPU not working

When I tried to use the most recent version of spacy (2.2.3) with the gpu from python on the terminal  I get the error `Segmentation fault (core dumped)`. When I try to run the same command from Jupyter notebook it crashes the kernel. Below the code:

 ```
import spacy
spacy.prefer_gpu()
```
I installed spacy with gpu support:

```
pip install -U spacy[cuda100]
```
I know there is not a lot of info about this error but it may be related to #1757?

Also spacy seems to be working when not setting `prefer_gpu`

## Your Environment

* Operating System: Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic
* Python Version Used: 3.6.9
* spaCy Version Used: 2.2.3
* Environment Information: conda 
* Model: en, en_core_web_md, en_core_web_lg, es_core_news_md

**Comment by adrianeboyd** [comment]
Hmm, it's hard to tell what might be going on. Some things to try to maybe narrow down the source of the problem:

* Does it work with spacy v2.1.9?

* Does it work if you just try something simple with cupy:

```
import cupy
cupy.zeros(1)
```

* Could you also try installing spacy without conda? Create a new venv with `python3 -m venv` and install with `pip`?

* And just to double-check: you're sure that CUDA has been installed correctly? You've compiled and run some of the sample CUDA programs or used the GPU successfully with other libraries? You've checked that 10.0 is the right CUDA version (`nvcc --version`)?

**Comment by jlealtru** [comment]
Hi Adriene,

Thanks for your prompt reply. Below you will find answers to your questions.

It is not working with spacy v2.1.9, I get the same error just trying to load the library.

It seems to be working with cupy on the conda enviroment.
```
import cupy
cupy.zeros(10)
```
It works fine using venv and python 3.7.4.

I have cuda  V10.0.130 as seen below and I can use pytorch 1.3 and transformers 2.2 without any problem.
![image](https://user-images.githubusercontent.com/4602712/71197810-6bdbe780-2260-11ea-92a6-23fa8894c884.png)

**Comment by svlandeg** [comment]
Hi @jlealtru, apologies for the late follow-up. It's always difficult to remotely debug installation issues. The information you provided doesn't immediately point us to an obvious reason for the original error. Is this still an open issue or have you been able to fix this in the meantime?

**Comment by umarbutler** [comment]
I just experienced this same error. I have previously trained models with my gpu on the same computer, using the same data, with no issues. After using venv to download and run spacy in a different project folder (while spacy was also running in the background), however, I got this error.

I then tried to train the model again, except this time using venv. That resulted in this error: "cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed."

After deactivating my other venv instance, and running spacy again (this time without venv), it worked.

It seems that venv _might_ have a role to play in this error (or perhaps running simultaneous instances of spacy?).

**Comment by jlealtru** [comment]
I solved this issue with the old method of deleting my environment and resintalling all the libraries again. Not sure if there is an easy fix for this bug.

**Comment by svlandeg** [comment]
Thanks for letting us know, @jlealtru !

I've noticed myself that GPU/notebook/venv can be a bit tricky sometimes. It's good to know that reinstalling in a clean env worked for you. I think that also means there's not really an action point on our side.
