### ISSUE TITLE
ImportError: [E048] Can't import language en from spacy.lang: cannot import name 'PRON_LEMMA' from 'spacy.symbols'

### ISSUE THREAD

**Issue by kzhou13** [explosion/spaCy#7820]
## How to reproduce the behaviour

```
from collections import Counter   #this package helps us get the most frequent words out of a list
import re    #we need this module to define regex
import os    
import os.path
import string
import nltk
from nltk.tokenize import MWETokenizer  #import tokenizer
from nltk import word_tokenize, pos_tag  #we need thse packages to identify the tense (future vs past) of a textual document
tokenizer = MWETokenizer()
nltk.download('stopwords')  #download the list of stopwords, if you have not already done so
from nltk.corpus import stopwords  #import the list of stopwords
from nltk.stem.snowball import SnowballStemmer  #import stemmer module
stemmer = SnowballStemmer('english')
import pandas as pd

pip install spacy==2.3.5

pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz



import spacy    #this package helps us identify location (cities, states, rivers etc.)

import en_core_web_sm
nlp = en_core_web_sm.load()
```

## Your Environment

* Operating System: Windows 
* Python Version Used: 3.8 
* spaCy Version Used: 2.3.5
* Environment Information: N/A

**Comment by adrianeboyd** [comment]
From the code posted here it's hard to tell where this error is coming from, but if you're getting an error related to `PRON_LEMMA` it probably means that you're working in an environment with spacy v3.0 instead of spacy v2.3.

**Comment by adrianeboyd** [comment]
Let me move this to the new discussion board...
