### ISSUE TITLE
Upgrade to spacy 3.7.2 throws Attribute error

### ISSUE THREAD

**Issue by srikanth-t20** [explosion/spaCy#13298]
'TransformerData' object has no attribute 'last_hidden_layer_state' while using pre-trained transformer model.

spaCy validate command returns success for version compat.

**Comment by danieldk** [comment]
Could you give the backtrace of where this error occurs or instructions how to reproduce this error?

Some background: prior to spaCy 3.7, the our pretrained pipelines used `spacy-transformers`, starting from 3.7.0 they use `spacy-curated-transformers`. However, both types of pipelines work with spaCy 3.7.0. This error seems to come from code that tries to use the `last_hidden_layer_state` property, which is only available in `spacy-curated-transformers` on transformer output that comes from `spacy-transformers`.

However, it is hard to say what code is error comes from without a backtrace of the exception.

**Comment by srikanth-t20** [comment]
Sure. Here it is:

Error type: <class 'AttributeError'>;
Error value: 'TransformerData' object has no attribute 'last_hidden_layer_state';
Error Trace: [<FrameSummary file ../../TrainSpacyModel.py, line 56 in trainSpacyModel>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/cli/train.py, line 84 in train>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/training/loop.py, line 135 in train>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/training/loop.py, line 118 in train>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/training/loop.py, line 243 in train_while_improving>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/training/loop.py, line 298 in evaluate>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/language.py, line 1459 in evaluate>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/language.py, line 1618 in pipe>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/util.py, line 1685 in _pipe>, <FrameSummary file spacy/pipeline/pipe.pyx, line 55 in pipe>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/util.py, line 1685 in _pipe>, <FrameSummary file spacy/pipeline/transition_parser.pyx, line 245 in pipe>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/util.py, line 1632 in minibatch>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/util.py, line 1685 in _pipe>, <FrameSummary file spacy/pipeline/transition_parser.pyx, line 245 in pipe>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/util.py, line 1632 in minibatch>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/util.py, line 1685 in _pipe>, <FrameSummary file spacy/pipeline/trainable_pipe.pyx, line 79 in pipe>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy/util.py, line 1704 in raise_error>, <FrameSummary file spacy/pipeline/trainable_pipe.pyx, line 75 in spacy.pipeline.trainable_pipe.TrainablePipe.pipe>, <FrameSummary file spacy/pipeline/tagger.pyx, line 138 in spacy.pipeline.tagger.Tagger.predict>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/thinc/model.py, line 334 in predict>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/thinc/layers/chain.py, line 54 in forward>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/thinc/model.py, line 310 in __call__>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy_curated_transformers/models/listeners.py, line 415 in last_transformer_layer_listener_forward>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/thinc/model.py, line 334 in predict>, <FrameSummary file /root/anaconda3/envs/spacy_bert_pt/lib/python3.7/site-packages/spacy_curated_transformers/models/pooling.py, line 103 in with_ragged_last_layer_forward>]

**Comment by danieldk** [comment]
Thank you, could you give more information about the model configuration and the `TrainSpacyModel.py` program that is in the backtrace?

What seems to be happening here is that the model is using a transformer from `spacy-transformers`, so a transformer pipe that is configured like this:

```
[components.transformer]
factory = "transformer"
# ...
```

But that the parser in the pipeline is configured with a listener from `spacy-curated-transformers`, e.g.:

```
[components.parser.model.tok2vec]
@architectures = "spacy-curated-transformers.LastTransformerLayerListener.v1"
width = 768
pooling = {"@layers":"reduce_mean.v1"}
upstream = "*"
```

However, that doesn't work. If the transformer is from `spacy-transformers`, then the listener should be from the same package. E.g.:


```
[components.parser.model.tok2vec]
@architectures = "spacy-transformers.TransformerListener.v1"
grad_factor = 1.0

[components.parser.model.tok2vec.pooling]
@layers = "reduce_mean.v1"
```

**Comment by danieldk** [comment]
> Question 1: In the section [components.transformer], what is the value for "factory" key that should be set for spacy-curated-transformer? Is it "curated-transformer"?

Yes indeed. But the `curated-transformer`, but you also have to changed the model that is used to the correct architecture. If you use `bert-base-uncased` that would be `spacy-curated-transformers.BertTransformer.v1`.

```
[components]

[components.transformer]
factory = "curated_transformer"

[components.transformer.model]
@architectures = "spacy-curated-transformers.BertTransformer.v1"
```

You can then fill the rest of the transformer and initialization configuration with [`init fill-curated-transformer`](https://spacy.io/api/cli#init-fill-curated-transformer), specifying the model name (`bert-base-uncased`) through the `--model-name` argument.

> Question 2: In the section [components.parser], we've set the key "source" to the transformer model (en_core_web_trf). Shouldn't it use the transformer-listener automatically?

There are two issues here:

1. The `parser` component of `en_core_web_trf` uses `LastTransformerLayerListener` as its tok2vec model. So that's what gets copied over when you are sourcing the other model.
2. When you change `components.transformer` to use `curated_transformer`, the `parser` listener will work. However it does not have the effect that you probably want, because it will use the new `transformer` component and not the transformer component from the `en_core_web_trf` pipe. So you'd mostly be training the `parser` and `tagger` components from scratch.

Could you give more information of what you are trying to accomplish? If your goal is to add an entity ruler to the pipe, it will be much easier to take the existing `en_core_web_trf` model and add the entity ruler to that.

**Comment by srikanth-t20** [comment]
Thank you for the update Daniel.

We are planning to build a custom NER along with entity ruler using pre-trained transformer model. 

Initially, there was an issue whose resolution implied that _tagger_ and _attribute_ruler_ should be added to the pipeline for using attribute POS while building entity rules. We expected the _tagger_ to pick the annotations from the pre-trained transformer. Hence set the source accordingly and included them in the frozen components list.

Coming back to the question that you raised, there wasn't any need for us to use _curated-transformer_. It was working fine pre-v3.7.2. After upgrading, it is trying to look for a non-existing member as mentioned in the issue description.

It seems that it is automatically loading the _curated-transformer_ without any explicit setting it in any of our config sections.

As suggested by you, I'll call the _init fill-curated-transformer_ to generate a full _config.cfg_ and see the complete list of changes made to the file in v3.7.2. 

Finally, can you please suggest a good documentation source that explains all the sections and their respective key/value pairs that are populated in the _config.cfg_ file?

Thanks again for your help.

**Comment by danieldk** [comment]
The main config sections are described here:

https://spacy.io/api/data-formats#config

spacy-transformers:

https://spacy.io/api/transformer#config
https://spacy.io/api/architectures#TransformerModel

curated-transformers:

https://spacy.io/api/curatedtransformer#config

We also have example configs/projects for transformers:

https://github.com/explosion/spacy-transformers/tree/master/examples/configs
https://github.com/explosion/spacy-curated-transformers/tree/main/project

**Comment by danieldk** [comment]
I'll close this issue, because it is about configuration and not a bug in spaCy itself. Feel free to open a discussion thread if you have follow-up questions.
