### ISSUE TITLE
STOPWORDS missing in 1.3.0

### ISSUE THREAD

**Issue by danweecc** [explosion/spaCy#687]
I've been trying this python 2.7.12 running on Ubuntu.

When I have spaCy 0.101.0 installed, I have no problems running:-

>>> import spacy
>>> spacy.en.STOPWORDS

which yields the list of stop words. However, with spaCy 1.3.0 installed, I get the following error:-

>>> spacy.en.STOPWORDS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'STOPWORDS'

Reverting to 0.101.0 causes the error to go away. Was there some change that happened with 1.3.0 with regards to the STOPWORDS functions?

In the same manner:

>>> nlp.is_stop('test')

works in 0.101.0 but in 1.3.0 I get:-

>>> nlp.is_stop('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'English' object has no attribute 'is_stop'

Would appreciate heads up - I can't find any documentation on the key changes in this regard. Thanks.

**Comment by ines** [comment]
Yes, the language data has moved since version 0.101.0. You can now find the stopwords in `spacy.en.language_data.STOP_WORDS` or `spacy.en.English.Defaults.stop_words`. I hope this helps!

**Comment by danweecc** [comment]
Thanks! This works perfectly!

**Comment by nscozzaro** [comment]
What worked for me is:
from spacy.lang.en import STOP_WORDS
