### ISSUE TITLE
Ukrainian model

### ISSUE THREAD

**Issue by 1ZvEzD1K1** [explosion/spaCy#11838]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_43/4138998002.py in <module>
      2 from spacy.lang.uk.examples import sentences
      3 
----> 4 nlp = spacy.load("uk_core_news_sm")
      5 doc = nlp(sentences[0])
      6 print(doc.text)

/srv/conda/envs/notebook/lib/python3.7/site-packages/spacy/__init__.py in load(name, vocab, disable, enable, exclude, config)
     58         enable=enable,
     59         exclude=exclude,
---> 60         config=config,
     61     )
     62 

/srv/conda/envs/notebook/lib/python3.7/site-packages/spacy/util.py in load_model(name, vocab, disable, enable, exclude, config)
    434     if name in OLD_MODEL_SHORTCUTS:
    435         raise IOError(Errors.E941.format(name=name, full=OLD_MODEL_SHORTCUTS[name]))  # type: ignore[index]
--> 436     raise IOError(Errors.E050.format(name=name))
    437 
    438 

OSError: [E050] Can't find model 'uk_core_news_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

**Comment by richardpaulhudson** [comment]
Have you downloaded the model using the command `python -m spacy download uk_core_news_sm`? (see https://spacy.io/usage).

**Comment by 1ZvEzD1K1** [comment]
yes but got a message in the console

my code:
import spacy

nlp = spacy.load("uk_core_news_sm")

text = 'доброго вечора мене звати сергій це служба підтримки гло чим можемо допомогти доброго чим мені дзвонили дзвонили я по суті побачу сергій двадцять три да сергій ви вже повнолітні та палите да да ну я вчені вже плюс жила у вас створено замовлення на пристрій гло а про слім золотого до жовтого кольору до це одна гривня двадцять копійок доставлення на місто київ відділення номер двісті сорок шість все вірно да до да ваша замовлення успішно підтверджено очікуйте будь ласка смс на номер нуль один два два нуль один три сповіщення від нової пошти дякую дякую дякую вам можливо я додаткові питання сергій ні все всіх все дякую дякую дякую вам на все добре гарного дня то бачу у'

doc = nlp(text)

print("Noun phrases:", [chunk.text for chunk in doc.noun_chunks])

for token in doc:
print(token.text)
output:
Traceback (most recent call last):
 File "/Users/user/Desktop/bat-transcribation/find_hide.py", line 3, in <module>
   nlp = spacy.load("uk_core_news_sm")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/__init__.py", line 54, in load
   return util.load_model(
          ^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/util.py", line 432, in load_model
   return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/util.py", line 468, in load_model_from_package
   return cls.load(vocab=vocab, disable=disable, enable=enable, exclude=exclude, config=config)  # type: ignore[attr-defined]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/uk_core_news_sm/__init__.py", line 10, in load
   return load_model_from_init_py(__file__, **overrides)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/util.py", line 649, in load_model_from_init_py
   return load_model_from_path(
          ^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/util.py", line 506, in load_model_from_path
   nlp = load_model_from_config(
         ^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/util.py", line 554, in load_model_from_config
   nlp = lang_cls.from_config(
         ^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/language.py", line 1818, in from_config
   nlp.add_pipe(
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/language.py", line 801, in add_pipe
   pipe_component = self.create_pipe(
                    ^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/language.py", line 680, in create_pipe
   resolved = registry.resolve(cfg, validate=validate)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/confection/__init__.py", line 728, in resolve
   resolved, _ = cls._make(
                 ^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/confection/__init__.py", line 777, in _make
   filled, _, resolved = cls._fill(
                         ^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/confection/__init__.py", line 849, in _fill
   getter_result = getter(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/lang/uk/__init__.py", line 46, in make_lemmatizer
   return UkrainianLemmatizer(
          ^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spacy/lang/uk/lemmatizer.py", line 31, in __init__
   self._morph = MorphAnalyzer(lang="uk")
                 ^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymorphy2/analyzer.py", line 224, in __init__
   self._init_units(units)
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymorphy2/analyzer.py", line 235, in _init_units
   self._units.append((self._bound_unit(unit), False))
                       ^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymorphy2/analyzer.py", line 246, in _bound_unit
   unit = unit.clone()
          ^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymorphy2/units/base.py", line 35, in clone
   return self.__class__(**self._get_params())
                           ^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymorphy2/units/base.py", line 76, in _get_params
   (key, getattr(self, key, None)) for key in self._get_param_names()
                                              ^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymorphy2/units/base.py", line 70, in _get_param_names
   args, varargs, kw, default = inspect.getargspec(cls.__init__)
                                ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

21 листопада 2022, 15:24:31, від "Richard Hudson" ***@***.***>:


Have you downloaded the model using the command python -m spacy download uk_core_news_sm? (see https://spacy.io/usage).

**Comment by adrianeboyd** [comment]
It looks like the current release of `pymorphy2` isn't compatible with python 3.11.

For now the best workaround is to use an older version of python.

**Comment by 1ZvEzD1K1** [comment]
But everything works without problems with the EU model

21 листопада 2022, 18:38:20, від "Adriane Boyd" ***@***.***>:


It looks like the current release of pymorphy2 isn't compatible with python 3.11.
For now the best workaround is to use an older version of python.

**Comment by adrianeboyd** [comment]
Do you mean the "en" model? The Russian and Ukrainian models use the extra third-party library pymorphy2 for lemmatization.

If you don't need lemmatization, it should also work on python 3.11 if you exclude the `lemmatizer` component from your pipeline:

```
nlp = spacy.load("uk_core_news_sm", exclude=["lemmatizer"])
```

**Comment by 1ZvEzD1K1** [comment]
thanks, will have to try it

21 листопада 2022, 19:36:08, від "Adriane Boyd" ***@***.***>:


Do you mean the "en" model? The Russian and Ukrainian models use the extra third-party library pymorphy2 for lemmatization.
If you don't need lemmatization, it should also work on python 3.11 if you exclude the lemmatizer component from your pipeline:
nlp = spacy.load("uk_core_news_sm", exclude=["lemmatizer"])

**Comment by 1ZvEzD1K1** [comment]
NotImplementedError: [E894] The 'noun_chunks' syntax iterator is not implemented for language 'uk'.
most of the errors disappeared, but 2 remained

21 листопада 2022, 19:36:08, від "Adriane Boyd" ***@***.***>:


Do you mean the "en" model? The Russian and Ukrainian models use the extra third-party library pymorphy2 for lemmatization.
If you don't need lemmatization, it should also work on python 3.11 if you exclude the lemmatizer component from your pipeline:
nlp = spacy.load("uk_core_news_sm", exclude=["lemmatizer"])

**Comment by 1ZvEzD1K1** [comment]
Hello, how can you configure the matcher so that it does not work for 100% matching?
It is necessary that he finds similar phrases or the same but with an error

**Comment by adrianeboyd** [comment]
Please start a new thread on the discussion board for new questions: https://github.com/explosion/spacy/discussions

There is work in progress on a fuzzy matching option for the matcher: https://github.com/explosion/spaCy/pull/11359
