### ISSUE TITLE
Poor performance of parser/tokenizer/tagger in v2

### ISSUE THREAD

**Issue by greatvovan** [explosion/spaCy#3375]
I am trying to migrate to version 2 because we also migrating to Python 3.7 and it seems there is no way to launch v1 on Python 3.7. I encountered significant performance degradation on our use case of working with the library.

```
import time
import spacy


spacy_nlp = spacy.load('en')


def file_lines_to_list(filename):
    result = []
    with open(filename, 'rt') as f:
        while True:
            line = f.readline()
            if line == '':
                break
            result.append(line.strip('"'))
    return result


texts = file_lines_to_list('articles_1000.tsv')
print(len(texts), 'texts loaded')

cnt = 0
start = time.time()
for text in texts:
    spacy_doc = spacy_nlp.tokenizer(text)
    spacy_nlp.parser(spacy_doc)
    spacy_nlp.tagger(spacy_doc)
    pos_tagged = [token.pos_ for token in spacy_doc]
    word_start = [token.idx for token in spacy_doc]
    cnt += 1
    if cnt % 100 == 0:
        print(cnt, 'texts done')
stop = time.time()
print(cnt, 'texts,', stop - start, 's')

# Let's figure out what steps take what time.
spacy_docs = [None] * len(texts)    # pre-allocate the list

start = time.time()
for i, text in enumerate(texts):
    spacy_docs[i] = spacy_nlp.tokenizer(text)
stop = time.time()
print('tokenizer:,', stop - start, 's')

start = time.time()
for sd in spacy_docs:
    spacy_nlp.parser(sd)
stop = time.time()
print('parser:,', stop - start, 's')

start = time.time()
for sd in spacy_docs:
    spacy_nlp.tagger(sd)
stop = time.time()
print('tagger:,', stop - start, 's')

start = time.time()
for sd in spacy_docs:
    pos_tagged = [token.pos_ for token in sd]
    word_start = [token.idx for token in sd]
stop = time.time()
print('iterate tokens:,', stop - start, 's')
```

The test data is 1000 English news articles, 5K–6K length. I can upload it if anybody needs, but I don't think any other test data shows different result.

I tested it on python:3.6.4 Docker image with the following results:

**Version 1.10.1:**
```
1000 texts, 25.532045602798462 s
tokenizer:, 2.1467573642730713 s
parser:, 13.970844268798828 s
tagger:, 3.700913429260254 s
iterate tokens:, 0.7997381687164307 s
```
During the computation it consumed 100% of CPU (looks like one core).

**Version 2.0.18:**
```
1000 texts, 189.37436604499817 s
tokenizer:, 5.186349391937256 s
parser:, 139.3413963317871 s
tagger:, 32.01847982406616 s
iterate tokens:, 0.4142322540283203 s
```
During the computation it consumed 400% of CPU. You did not misread it, **It works 7.5 times longer and consumes 4 times more CPU**! So I would estimate the total degradation as 30 times.

We cannot proceed with this performance degradation, is there any way to speed up this?

What also raises some questions, is that v2.0.18 works little bit better natively on my Mac's Python 3.7:
```
1000 texts, 127.95850396156311 s
tokenizer:, 20.903636932373047 s
parser:, 79.46765208244324 s
tagger:, 20.6867458820343 s
iterate tokens:, 0.3974919319152832 s
```
CPU: ~200%

Though it is still not good at all, it little bit better, which suggests the result may depend on compilers/compiler options or other OS related things.

If we change initialization of `texts` like this:
```
texts = ['Quick brown fox'] * 30000
```
we will see a bit different side of the problem. This works extremely fast on version 1 (~1 second), but insanely slow on version 2. I can conclude that the degradation is not that dramatic for large texts, but very significant on big sets of short texts (with the slowest part remaining parser). This brings us to an assumption that launching parser's internals has become a heavy thing in v2.

## Environment
Docker Desktop for Mac 2.0.0.3 with 4 cores dedicated to Docker daemon.
Mac OS 10.14.3

Originally the degradation was discovered on Docker under Ubuntu, I just used Docker on my Mac to run more specific tests.

In all cases the library is installed through `pip install spacy==X.X.X`

**Comment by honnibal** [comment]
Try `spacy-nightly`. The main problem is that the matrix multiplications in v2.0 were performed via numpy, which can be linked against a variety of backends, some of which perform very poorly. The backend also often launches too many threads, especially in Docker containers, where it thinks it has access to the whole CPU.

The solution took a lot of effort. After trying a lot of things that didn't work, I've managed to package the Blis linear algebra routines such that they can be installed from any OS, on both pip and conda. The packed version is single-threaded, removing the problem of too many threads being launched. This does mean you have to use multi-processing to parallelise, but it means you can parallelise at the outermost layer, which is much more efficient in total.

When you install v2.1, be sure to update your models. The models are not compatible between v2.0 and v2.1.

In future we may release a linear model for v2.1 as well, although it's not a big priority.

**Comment by greatvovan** [comment]
Tried the same with the latest `nightly` 2.1.0a. Indeed it uses only one core and at the same time it performs at faster speed (~ 2 times), but still it is far from performance of v1.

How hard is it to just make v1.* runnable on Python 3.7?

**Comment by honnibal** [comment]
Try using `nlp.pipe()` instead of successive calls to `nlp()`. It will allow it to minibatch, which should make things a bit faster too.

I don't know how hard it would be to get 1.x working on 3.7. I guess you could try? What's the error you get?

**Comment by greatvovan** [comment]
As for the suggestion with `pipe()`, I am just simulating what happens in real application, I guess some calls may be piped, but not many.

When I launch `pip install spacy==1.10.1` on a Python 3.7 image the build fails for `spacy`, `thinc` and `cytoolz`, all with a similar error:
```
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.7/cytoolz/dicttoolz.o
    cytoolz/dicttoolz.c: In function ‘__Pyx_PyCFunction_FastCall’:
    cytoolz/dicttoolz.c:8277:13: error: too many arguments to function ‘(PyObject * (*)(PyObject *, PyObject * const*, Py_ssize_t))meth’
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cytoolz/dicttoolz.c: In function ‘__Pyx__ExceptionSave’:
    cytoolz/dicttoolz.c:9053:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
         *type = tstate->exc_type;
                       ^~
    cytoolz/dicttoolz.c:9054:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
         *value = tstate->exc_value;
                        ^~
    cytoolz/dicttoolz.c:9055:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
         *tb = tstate->exc_traceback;
                     ^~
    cytoolz/dicttoolz.c: In function ‘__Pyx__ExceptionReset’:
    cytoolz/dicttoolz.c:9062:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
         tmp_type = tstate->exc_type;
                          ^~
    cytoolz/dicttoolz.c:9063:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
         tmp_value = tstate->exc_value;
                           ^~
    cytoolz/dicttoolz.c:9064:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
         tmp_tb = tstate->exc_traceback;
                        ^~
    cytoolz/dicttoolz.c:9065:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
         tstate->exc_type = type;
               ^~
    cytoolz/dicttoolz.c:9066:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
         tstate->exc_value = value;
               ^~
    cytoolz/dicttoolz.c:9067:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
         tstate->exc_traceback = tb;
               ^~
    cytoolz/dicttoolz.c: In function ‘__Pyx__GetException’:
    cytoolz/dicttoolz.c:9122:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
         tmp_type = tstate->exc_type;
                          ^~
    cytoolz/dicttoolz.c:9123:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
         tmp_value = tstate->exc_value;
                           ^~
    cytoolz/dicttoolz.c:9124:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
         tmp_tb = tstate->exc_traceback;
                        ^~
    cytoolz/dicttoolz.c:9125:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
         tstate->exc_type = local_type;
               ^~
    cytoolz/dicttoolz.c:9126:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
         tstate->exc_value = local_value;
               ^~
    cytoolz/dicttoolz.c:9127:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
         tstate->exc_traceback = local_tb;
               ^~
    error: command 'gcc' failed with exit status 1
```

**Comment by honnibal** [comment]
I think that error will be easy to fix. I guess the Python C API changed, so the `.cpp` files that the pip packages come with are out of date. If you check out the version tags you're using from the source repo and build from source, you can probably generate a package that works for you.

**Comment by greatvovan** [comment]
@honnibal yes, I also tried this, even more frustrating...

I do:
```
docker run -it --rm python:3.7 bash
pip install cython
pip install thinc==6.12.1
git clone https://github.com/explosion/spaCy/
cd spaCy/
git checkout v1.10.1
pip install -e .
```
(as suggested in https://github.com/explosion/spaCy/blob/v1.10.1/README.rst).
After a few warnings about `language_level` it fails with:
```
Error compiling Cython file:
    ------------------------------------------------------------
    ...
            else:
                t.idx = (t-1).idx + (t-1).lex.length + (t-1).spacy
            t.l_edge = self.length
            t.r_edge = self.length
            assert t.lex.orth != 0
            t.spacy = has_space
                     ^
    ------------------------------------------------------------
    doc.pyx:471:18: undeclared name not builtin: has_space
```
The place it complains on appears to be this:
https://github.com/explosion/spaCy/blob/v1.10.1/spacy/tokens/doc.pyx#L471
But it makes absolutely no sense to me, because `has_space` is a formal parameter of `push_back()` function, it is unclear why it considers it "undeclared".

**Comment by greatvovan** [comment]
It seems like I managed to build it under Python 3.7. Here what I did:

1. Installed latest Cython
2. Changed `thinc` version in the dependencies to 6.12.1 (since the version from the actual `requirements.txt` is not compatible with Python 3.7 too).
3. Renamed `trailing_space` variable into `has_space` in https://github.com/explosion/spaCy/blob/v1.10.1/spacy/tokens/doc.pxd#L56 to make parameter names match in in declaration and definition (as Cython apparently became sensitive to this sort of things).
4. Changed `for byte in self.data[start_byte:]:` in https://github.com/explosion/spaCy/blob/v1.10.1/spacy/serialize/bits.pyx#L57 into
```
        ending = self.data[start_byte:]
        cdef uchar* c_str_ending = ending
        for byte in c_str_ending:
```
5. Added Cython directives in https://github.com/explosion/spaCy/blob/v1.10.1/bin/cythonize.py#L58: `-X annotation_typing=False` (just in case, because the default value has changed) and `-X language_level=2` (to eliminate the warning in newer version).

After this `pip install -e .` succeeded.

I also ran tokenization/parsing/tagging on a number of texts and checked it produces the same output as the "original" version 1.10.1. The speed is awesome, I have my performance back with Python 3.7!

I also tried running tests (as described in the main readme) but they fail. Although I need to say that tests on v1.10.1 installed with pip fail as well, probably they are broken at this commit/tag.

I would appreciate if somebody estimated that my approach is sane/adequate. I also a bit worried that I use not originally required `thinc` lib version, is it important for parser/tagger?
