### ISSUE TITLE
SPACY IMPORT ERROR! 

### ISSUE THREAD

**Issue by memora0101** [explosion/spaCy#6368]
## How to reproduce the problem

"I've tried updating new versions of thinc and spacy as directed from previous issue posts." Its flagging a import error.

```bash
# copy-paste the error message here
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-cb604e7f192b> in <module>
      1 import pandas as pd
      2 import string
----> 3 import spacy
      4 from collections import Counter
      5 from spacy.lang.en import English

~/opt/anaconda3/lib/python3.7/site-packages/spacy/__init__.py in <module>
      8 
      9 # These are imported as part of the API
---> 10 from thinc.api import prefer_gpu, require_gpu  # noqa: F401
     11 from thinc.api import Config
     12 

ImportError: cannot import name 'prefer_gpu' from 'thinc.api' (/Users/lexroverts/opt/anaconda3/lib/python3.7/site-packages/thinc/api.py)

## Your Environment

* Operating System:IOS Mac
* Python Version Used: 3.7.6
* spaCy Version Used:  2.1.8
* Environment Information:
<img width="1085" alt="Screen Shot 2020-11-09 at 2 23 33 PM" src="https://user-images.githubusercontent.com/65258221/98592332-30db0c00-2297-11eb-962e-637d988c140d.png">

I need help trying to get spacy to work again on Jupiter notebooks.

**Comment by memora0101** [comment]
This is the errors I get when updating Thinc. 
please advice on a solution.

<img width="1216" alt="Screen Shot 2020-11-09 at 6 12 55 PM" src="https://user-images.githubusercontent.com/65258221/98611279-42341080-22b7-11eb-9470-5878cc6f129d.png">

**Comment by adrianeboyd** [comment]
`pip` lets you update packages even if this might cause conflicts with other currently installed packages. Notice the warnings at the bottom of the install message that show which packages are incompatible. Updating `thinc` independently from `spacy` can lead to mismatches. (In general it's easier for us to help if the errors are pasted as text in a code block instead of as images, thanks!)

You may be able to fix your current virtual environment with `pip install spacy==2.3.2`. You also don't want to have `spacy` and `spacy-nightly` installed in the same environment, so please uninstall with `pip uninstall spacy-nightly`. (Unless you want the prerelease version, then uninstall `spacy` and follow install instructions here: https://nightly.spacy.io/usage)

If that doesn't work, we'd recommend starting with a new virtual environment and just installing spacy (`pip install spacy`, optionally with the stable version you'd like), which will pull in the correct versions of all the dependencies.

**Comment by memora0101** [comment]
Thank you for the recommendations, everything seems to work with thinc.
the only issue now is the importing error for the English model as follows:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-cb604e7f192b> in <module>
      3 import spacy
      4 from collections import Counter
----> 5 from spacy.lang.en import English
      6 from spacy.lang.en.stop_words import STOP_WORDS

ImportError: cannot import name 'English' from 'spacy.lang.en' (unknown location)

**Comment by adrianeboyd** [comment]
It can depend on which version of spacy you're using, although I think this has been the same for all v2 versions. `from spacy.lang.en.stop_words import STOP_WORDS` definitely works in spacy v2.3.2.

Could you provide the output of `python -m spacy info --markdown` for your new install?

**Comment by memora0101** [comment]
@adrianeboyd here is the following output after running python -m spacy info --markdown:

(base) Lexs-MacBook-Pro:~ lexroverts$ python -m spacy info --markdown

## Info about spaCy

* **spaCy version:** 2.3.2
* **Platform:** Darwin-19.6.0-x86_64-i386-64bit
* **Python version:** 3.7.6

**Comment by adrianeboyd** [comment]
Glad to hear it's working!
