### ISSUE TITLE
AttributeError: type object 'EnglishDefaults' has no attribute 'create_tokenizer'

### ISSUE THREAD

**Issue by bycloudai** [explosion/spaCy#7397]
## How to reproduce the behaviour
```
>>> from spacy.lang.en import English
>>> tokenizer = English().Defaults.create_tokenizer()
```
and I get this error

![image](https://user-images.githubusercontent.com/29135514/110334683-fd9a6500-805d-11eb-95c2-9be0c24618e6.png)

How can I make this work without running into an error?
My system default is English, but I also use Chinese.

I'll put this here if it helps. 
```
PS C:\WINDOWS\system32> dism /online /get-intl
...
Default system UI language : en-US
System locale : en-US
...
Installed language(s): en-US
  Type : Fully localized language.
Installed language(s): zh-TW
  Type : Partially localized language, MUI type.
  Fallback Languages en-US
```
![image](https://user-images.githubusercontent.com/29135514/110639642-eb016680-81ea-11eb-95c7-62048fb1fe43.png)

tag: @billagee

## Your Environment

* Operating System: Windows 10 insider build 21327
* Python Version Used: 3.7
* spaCy Version Used: 3.0.3
* Environment Information: WSL2 Ubuntu 18.04

**Comment by polm** [comment]
So that code works with spacy 2.3.0, but not with v3. The `create_tokenizer` function is basically an internal implementation detail and not really a public API. 

What are you trying to do exactly? If you just want to use spaCy as a tokenizer, normally you could use `spacy.blank("en")` or use a small model and disable pipelines. 

Also, as a note, spaCy doesn't use your locale settings for anything, so the language your computer is in shouldn't affect how spaCy behaves.

**Comment by polm** [comment]
Since this is a usage-related question, I'm going to move it to a discussion - you'll see that this issue is closed, but if you click on the link at the bottom you can follow up in the discussions forum.
